### ISSUE TITLE
Compatibility with y_hooks

### ISSUE THREAD

**Issue by FabricioAndre** [Open-GTO/zlang#3]
When we use this include with Y_hooks, the text returns "Error: Invalid Lang"

it doesn't work:
```
hook OnGameModeInit()
{
        LANG = Lang_Add("lang", "lang_name"); 
        Lang_LoadFile(LANG, "directory");
	return 1;
}
```

It works:
```
public OnGameModeInit()
{
        LANG = Lang_Add("lang", "lang_name"); 
        Lang_LoadFile(LANG, "directory");
	return 1;
}
```

**Comment by ziggi** [comment]
I just tested this and everything works fine for me. Try to make small script where the problem happens and send it to me.
