### ISSUE TITLE
y_hooks conflict

### ISSUE THREAD

**Issue by FabricioAndre** [Open-GTO/zlang#4]
i already opened a topic about that, you said (ZiGGi) there's no errors.
Always returns "Invalid Lang" because zlang_OnGameModeInit calls after y_hooks (hook OnGameModeInit)

[image 1](https://imgur.com/a/s05NI)
[image 2](https://imgur.com/a/6zwGO)
[image 3](https://imgur.com/a/uylph)

**Comment by ziggi** [comment]
I don't know how y_hooks works, but try to put the `#include <zlang>` line before the `#include <YSI/y_hooks>` line.

**Comment by FabricioAndre** [comment]
Yes, I ended up figuring it out myself, but other people are going to have problems if they don't know it.

Try this:

```
#if defined _inc_y_hooks || defined _INC_y_hooks
	#error please include zlang before y_hooks.
#endif
```

**Comment by ziggi** [comment]
Fixed.
