### ISSUE TITLE
Возвращение текста.

### ISSUE THREAD

**Issue by ynhhoJ** [Open-GTO/zlang#5]
Заметил что в zlang нету функции которая возрвращает только текст на языке который использует игрок, поэтому я хочу предложить свой вариант. Это может быть полезно когда нужно возвращать только текст в диалоге используя "shorthand".
Пример:
```pawn
if(...) == 1 ? (Lang_ReturnOnlyText(playerid,"TEXT")) : (Lang_ReturnOnlyText(playerid,"ANOTHER_TEXT"))
```
Сама функция:
```pawn
stock Lang_ReturnOnlyText(playerid, var[], lang_args<>){
	static
		text[MAX_LANG_FORMAT_STRING];
	Lang_GetText(Lang_GetPlayerLang(playerid), var, text);
	Lang_format(text, sizeof(text), text, lang_start<2>);
	return text;
}
````

**Comment by ziggi** [comment]
Так лучше не делать, так как это приводит к большому потреблению стека (5к). Я бы оставил это, но для корректной работы (для поддержки мультистрочности) нужно использовать размер MAX_LANG_MFORMAT_STRING, а в этом случае использование стека стремится к 20к ячейкам.

Вот код и названия функций, которые я бы рекомендовал использовать, но включать в основной скрипт не хочу:
```Pawn
stock Lang_ReturnText(Lang:lang, const var[], lang_args<>)
{
	static
		text[MAX_LANG_FORMAT_STRING];

	Lang_GetText(lang, var, text);
	Lang_format(text, sizeof(text), text, lang_start<2>);
	return text;
}

#define Lang_ReturnPlayerText(%0, Lang_ReturnText(Lang_GetPlayerLang(%0),
#define Lang_ReturnDefaultText( Lang_ReturnText(Lang_GetDefaultLang(),
```
