### ISSUE TITLE
Добавление поддержки тегов

### ISSUE THREAD

**Issue by ghost** [Open-GTO/zlang#7]
Здравствуйте! У меня есть предложение по улучшению вашего плагина: добавить возможность использовать теги для чата (ну или пример, как можно всё сделать). Не знаю, насколько это необходимо и эффективно, но я у меня получилось сделать эту функцию без поддержки аргументов (я пытался добавить поддержку тегов с необязательными аргументами используя код zlang.inc, но ничего не вышло)

TAG_ERROR  — для переведённого текста
TAG_ERROR2 — для текста, который не нужно переводить

```
#define Lang_SendText		LST
#define Lang_SendTextToAll	LSTTA

stock SCM_ERROR(playerid, const message[]) return LST(playerid, "TAG_ERROR", message);
stock SCM_ERROR2(playerid, const message[]) return LST(playerid, "TAG_ERROR2", message);

// ru.ini
TAG_ERROR = \v(COLOR_RED)[Ошибка]\v(COLOR_GREY): \v(%s)
TAG_ERROR2 = \v(COLOR_RED)[Ошибка]\v(COLOR_GREY): %s

comPlayerIsNotAdmin = Недостаточно прав!

// Пример:
SCM_ERROR(playerid, "comPlayerIsNotAdmin");
SCM_ERROR2(playerid, "ID Интерьера должен быть от 0 до 145.");
```

**Comment by ziggi** [comment]
Ничего не понял, что за теги?

**Comment by ghost** [comment]
Теги для чата в SAMP
Подсказка, Ошибка, Информация и т.п

![image](https://github.com/user-attachments/assets/31752cd9-efba-4d89-965e-dafd7d97f534)

А так это просто идея

**Comment by ziggi** [comment]
Дак можно же сделать так:
```ini
TAG_ERROR = \v(COLOR_RED)[Ошибка]\v(COLOR_GREY):

ERROR_comPlayerIsNotAdmin = \v(TAG_ERROR) Недостаточно прав!
```

```pawn
Lang_SendText(playerid, "ERROR_comPlayerIsNotAdmin");
```

Или так:
```ini
TAG_ERROR = \v(COLOR_RED)[Ошибка]\v(COLOR_GREY):

comPlayerIsNotAdmin = \v(%s) Недостаточно прав!
```

```pawn
Lang_SendText(playerid, "comPlayerIsNotAdmin", "TAG_ERROR");
```

Ну или как ты написал. Даже не знаю как это можно сделать как-то по-другому.

**Comment by ghost** [comment]
Внатуре, всё работает и оказывается не надо изобретать велосипед
Над этим голову ломал.

Спасибо, Ziggi!
